apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app-container
        image: sthakur410/testrepo:firstpush
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 7000
---
  apiVersion: v1
  kind: Service                    # Type of kubernetes resource
  metadata:
    name: my-go-app-service   # Name of the resource
  spec:
    type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
    ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
    - name: http
      port: 9090
      targetPort: 7000
    selector:
      app: go-app         # Map any pod with label `app=go-hello-world` to this service